# cloudbuild.yaml - Trigger smoke build (service_account ile uyumlu)
steps:
  - name: gcr.io/cloud-builders/gcloud
    id: Validate-GCloud
    args:
      - version

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 300s